made script for making array samplesheet
molgenis/ngs-utils pull request #228
Opened 2021-03-05 13:35 UTC by BenjaminsM

- must be executed as the dm user of the group on one of the prm systems
- samplesheet contains double samples, because some samplesheets are stored on both prm05 and prm06
- Copies scandata to one folder on prm, for use in genomestudio (since arraydata can be stored on both prm05 and prm06)

2021-03-08 08:20 UTC, RoanKanninga requested changes

2021-03-08 08:20 UTC, RoanKanninga commented on makeArrayReferenceSamplesheet.sh
> +        if grep "${line}" /groups/umcg-gap/prm0*/Samplesheets/archive/*.csv
quotes

2021-03-08 08:20 UTC, RoanKanninga commented on makeArrayReferenceSamplesheet.sh
> +        ls -latrh /groups/umcg-gap/prm0*/rawdata/array/IDAT/"${col1}/${col1}_${col2}"*.idat
quotes

2021-03-08 08:20 UTC, RoanKanninga commented on makeArrayReferenceSamplesheet.sh
> +        rsync -av /groups/umcg-gap/prm0*/rawdata/array/IDAT/"${col1}/${col1}_${col2}"*.idat "${workDirectory}/scanData"
quotes

2021-03-08 08:20 UTC, RoanKanninga commented on makeArrayReferenceSamplesheet.sh
> +                echo "cannot find ${line}"
ik denk dat het wel netter is als je dit ook even wegschrijft naar een file? Dat je die missing.txt oid noemt, anders weet je niet welke overgeslagen zijn?

2021-03-08 08:20 UTC, RoanKanninga commented on makeArrayReferenceSamplesheet.sh
> +mkdir -p ${workDirectory}
quotes

2021-03-10 16:06 UTC, RoanKanninga commented on makeArrayReferenceSamplesheet.sh
> +                echo "cannot find ${line}" >> "${missingSamplesFile}"
ik zou deze file eerst wel weggooien en dan touchen net zoals bij regel 79/80 voor de outputFile is gebeurd. Stel je voor dat je iets 2 of 3 keer draait krijg je een steeds langer wordende file

2021-03-11 09:20 UTC, pneerincx commented on makeArrayReferenceSamplesheet.sh
> +touch "${outputFile}"
Je kunt de combinatie van rm en touch samenvoegen met alleen:
`printf '' > "${outputFile}"`
De ' en ' na de printf zijn twee enkele quotes na alkaar en geen dubbele quote. Je schrijft dan dus een lege string naar `"${outputFile}"`. Als die al bestond wordt die overschreven en anders aangemaakt.
Hetzelfde kun je doen voor de `"${missingSamplesFile}"`.

2021-03-11 15:35 UTC, RoanKanninga commented on makeArrayReferenceSamplesheet.sh
> +touch "${outputFile}"
ja waar ik dus nat ging is dat ik het volgende deed:
echo "" > "${outputFile}"

als je later in het script de outputfile parsed stuiterd ie op de eerste regel, omdat die leeg is.
Pieter zn oplossing is inderdaad de goede, een printf '' > "${outputFile}"

2021-03-11 16:52 UTC, pneerincx approved these changes

2021-03-12 08:21 UTC, RoanKanninga approved these changes

2021-03-12 08:22 UTC, merged